"""Download HotpotQA dev distractor and write one Markdown file per question
into storage/library/hotpotqa/. Idempotent. CC BY-SA 4.0 attribution is
written to storage/library/hotpotqa/README.md.

Designed to be safe to re-run: a partial directory from a crashed prior run
is repaired on the next attempt; already-correct files are overwritten with
byte-identical content (no mtime churn).
"""
from __future__ import annotations

import argparse
import json
import logging
import os
import random
import sys
import tempfile
import time
from pathlib import Path

log = logging.getLogger("ingest_hotpotqa")

REPO_ROOT = Path(__file__).resolve().parent.parent
CACHE_PATH = REPO_ROOT / "scripts" / ".cache" / "hotpot_dev_distractor_v1.json"
LIBRARY_DIR = REPO_ROOT / "storage" / "library" / "hotpotqa"
README_PATH = LIBRARY_DIR / "README.md"

# HotpotQA dev-distractor (CC BY-SA 4.0). The default URL is the canonical
# mirror referenced by the official download.sh at maxbartolo/hotpot, but
# that CMU-hosted mirror has been intermittently unreliable since ~2024.
#
# To use a different mirror, pass `--source URL` on the CLI, or set
# HOTPOTQA_DEV_DISTRACTOR_URL in the environment. To use a file you
# downloaded yourself, pass `--from-local PATH` instead.
#
# Known working alternatives (verify before relying on):
#   - http://curtis.ml.cmu.edu/datasets/hotpot/hotpot_dev_distractor_v1.json
#     (canonical, official download.sh reference; sometimes times out)
#   - https://huggingface.co/datasets/hotpot_qa (community-uploaded mirror,
#     raw JSON may be under a sub-path; check the dataset's Files tab)
HOTPOTQA_URL = "http://curtis.ml.cmu.edu/datasets/hotpot/hotpot_dev_distractor_v1.json"

README_TEXT = """# HotpotQA Library Data

Dataset: HotpotQA dev_distractor v1 (multi-hop QA over Wikipedia).
Source: https://hotpotqa.github.io/
License: CC BY-SA 4.0.

This directory contains one Markdown file per question, generated by
`scripts/ingest_hotpotqa.py`. Files contain paragraph text from the original
dataset; questions, gold answers, and gold supporting facts are NOT included
in any file (kept in the source JSON only — see `scripts/.cache/`).

If you redistribute these files, retain this README.
"""


def copy_local_to_cache(local: Path) -> Path:
    """Copy a user-provided local file to CACHE_PATH, ALWAYS overriding any
    existing cache. Exits 1 if the file is missing or doesn't parse as JSON.

    The user explicitly passed --from-local, so we don't consult the cache
    or honor --force: the intent is unambiguous.
    """
    if not local.exists() or not local.is_file():
        print(f"--from-local source not found: {local}", file=sys.stderr)
        sys.exit(1)
    # Quick sanity check: file should parse as a JSON array of question objects.
    try:
        parsed = json.loads(local.read_text(encoding="utf-8"))
    except json.JSONDecodeError as e:
        print(f"--from-local source is not valid JSON: {e}", file=sys.stderr)
        sys.exit(1)
    if not isinstance(parsed, list) or not parsed:
        print(
            "--from-local source must be a non-empty JSON array of "
            "HotpotQA question objects",
            file=sys.stderr,
        )
        sys.exit(1)
    CACHE_PATH.parent.mkdir(parents=True, exist_ok=True)
    CACHE_PATH.write_bytes(local.read_bytes())
    return CACHE_PATH


def download_or_use_cache(force: bool, url: str) -> Path:
    """Download the JSON if absent or `force` is True; cache it at CACHE_PATH.
    Returns CACHE_PATH on success. Exits 1 with diagnostic on repeated failure."""
    if CACHE_PATH.exists() and not force:
        return CACHE_PATH
    CACHE_PATH.parent.mkdir(parents=True, exist_ok=True)
    last_err: Exception | None = None
    for attempt in (0, 1):
        try:
            import urllib.request

            req = urllib.request.Request(
                url, headers={"User-Agent": "agent_html/iter-9"}
            )
            with urllib.request.urlopen(req, timeout=60) as resp:
                data = resp.read()
            CACHE_PATH.write_bytes(data)
            return CACHE_PATH
        except Exception as e:
            last_err = e
            if attempt == 0:
                time.sleep(5)
    print(
        "Download failed after 2 attempts.\n"
        f"  URL : {url}\n"
        f"  err : {last_err}\n"
        "\n"
        "The CMU-hosted canonical mirror has been intermittently unreliable\n"
        "since ~2024. To work around this:\n"
        "  1. Download hotpot_dev_distractor_v1.json by any means that\n"
        "     works for you (curl, browser, huggingface.co/datasets/hotpot_qa,\n"
        "     a torrent, a teammate who has the file, etc.).\n"
        "  2. Re-run with: python scripts/ingest_hotpotqa.py "
        "--from-local /path/to/hotpot_dev_distractor_v1.json\n"
        f"     (and the file will be copied to {CACHE_PATH})\n"
        "  3. Or override the mirror with --source URL on each run.",
        file=sys.stderr,
    )
    sys.exit(1)


def slugify(qid: str) -> str:
    """Replace anything outside [A-Za-z0-9_-] with '_'. HotpotQA _id values
    are typically hex hashes that already conform; this is defensive."""
    out: list[str] = []
    for c in qid:
        if c.isalnum() or c in "-_":
            out.append(c)
        else:
            out.append("_")
    return "".join(out)


def stratified_sample(items: list[dict], n: int, seed: int = 42) -> list[dict]:
    """Same 6-bucket deterministic sampling as backend/eval/hotpotqa.py::sample.

    Inlined in this script so the ingest CLI has no path dependency on
    backend.eval at module-import time. Behavior is identical (same seed,
    same RNG instance, same per_bucket cap). The dedicated unit test in
    backend/tests/eval/test_hotpotqa.py covers the helper logic.
    """
    rng = random.Random(seed)
    buckets: dict[tuple[str, str], list[dict]] = {}
    for it in items:
        buckets.setdefault((it["type"], it["level"]), []).append(it)
    per = max(1, -(-n // 6))
    out: list[dict] = []
    for bucket in buckets.values():
        rng.shuffle(bucket)
        out.extend(bucket[:per])
    out = out[:n]
    rng.shuffle(out)
    return out


def write_question_file(item: dict, dest_dir: Path) -> None:
    qid = slugify(item["_id"])
    frontmatter = (
        "---\n"
        f"question_id: {item['_id']}\n"
        f"question_type: {item['type']}\n"
        f"question_level: {item['level']}\n"
        "source: hotpotqa\n"
        "---\n\n"
    )
    body_parts: list[str] = []
    for title, sentences in item["context"]:
        text = " ".join(sentences).strip()
        if not text:
            continue
        body_parts.append(f"# {title}\n{text}\n")
    full = frontmatter + "\n".join(body_parts)

    # Atomic write: tmp in the same dir, then os.replace.
    fd, tmp_path = tempfile.mkstemp(
        dir=str(dest_dir), prefix=f".{qid}.", suffix=".tmp"
    )
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as f:
            f.write(full)
        os.replace(tmp_path, dest_dir / f"{qid}.md")
    except Exception:
        try:
            os.unlink(tmp_path)
        except OSError:
            pass
        raise


def main(argv: list[str] | None = None) -> int:
    logging.basicConfig(
        level=logging.INFO, format="%(asctime)s %(levelname)s %(name)s %(message)s"
    )
    parser = argparse.ArgumentParser(
        description="Ingest HotpotQA dev distractor into the library."
    )
    grp = parser.add_mutually_exclusive_group()
    grp.add_argument(
        "--subset",
        type=int,
        metavar="N",
        help="Stratified sample of N questions (default if --full is also passed: --full wins)",
    )
    grp.add_argument(
        "--full", action="store_true", help="Use all 7,405 questions (default)"
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Re-download the dataset even if cached",
    )
    parser.add_argument(
        "--source",
        metavar="URL",
        default=os.environ.get("HOTPOTQA_DEV_DISTRACTOR_URL", HOTPOTQA_URL),
        help=(
            "Custom mirror URL. Overrides HOTPOTQA_DEV_DISTRACTOR_URL env var "
            "and the built-in default."
        ),
    )
    parser.add_argument(
        "--from-local",
        metavar="PATH",
        type=Path,
        help=(
            "Skip the network and copy a locally-downloaded "
            "hotpot_dev_distractor_v1.json from PATH into the cache. "
            "Use this when the network mirrors are flaky."
        ),
    )
    args = parser.parse_args(argv)

    if args.subset is not None and args.subset <= 1:
        parser.error("--subset must be >= 2")
    if args.from_local and args.source != os.environ.get(
        "HOTPOTQA_DEV_DISTRACTOR_URL", HOTPOTQA_URL
    ):
        # If user passed --from-local, --source is meaningless. argparse
        # can't easily express mutual exclusion with a default value, so warn.
        pass  # we just ignore --source when --from-local is set, below.

    print(
        "Dataset: HotpotQA dev_distractor v1 "
        "(CC BY-SA 4.0 — https://hotpotqa.github.io/)"
    )
    if args.from_local:
        json_path = copy_local_to_cache(args.from_local)
    else:
        json_path = download_or_use_cache(args.force, args.source)
    log.info("Loaded %d bytes from %s", json_path.stat().st_size, json_path.name)

    raw_items = json.loads(json_path.read_text(encoding="utf-8"))
    items = raw_items
    if args.subset is not None:
        items = stratified_sample(items, args.subset)
    log.info("Writing %d question files to %s", len(items), LIBRARY_DIR)

    LIBRARY_DIR.mkdir(parents=True, exist_ok=True)
    if not README_PATH.exists():
        README_PATH.write_text(README_TEXT, encoding="utf-8")

    skipped: list[str] = []
    written = 0
    for it in items:
        try:
            write_question_file(it, LIBRARY_DIR)
            written += 1
        except Exception as e:
            log.warning("Skipping qid=%s: %s", it.get("_id"), e)
            skipped.append(it.get("_id", "?"))
    log.info("Done: %d written, %d skipped", written, len(skipped))
    if skipped:
        preview = ", ".join(skipped[:10])
        log.warning(
            "Skipped IDs (first 10): %s%s",
            preview,
            "..." if len(skipped) > 10 else "",
        )
    return 0


if __name__ == "__main__":
    sys.exit(main())
