"""Download HotpotQA dev distractor and write one Markdown file per question
into storage/library/hotpotqa/. Idempotent. CC BY-SA 4.0 attribution is
written to storage/library/hotpotqa/README.md.

Designed to be safe to re-run: a partial directory from a crashed prior run
is repaired on the next attempt; already-correct files are overwritten with
byte-identical content (no mtime churn).
"""
from __future__ import annotations

import argparse
import json
import logging
import os
import random
import sys
import tempfile
import time
from pathlib import Path

log = logging.getLogger("ingest_hotpotqa")

REPO_ROOT = Path(__file__).resolve().parent.parent
CACHE_PATH = REPO_ROOT / "scripts" / ".cache" / "hotpot_dev_distractor_v1.json"
LIBRARY_DIR = REPO_ROOT / "storage" / "library" / "hotpotqa"
README_PATH = LIBRARY_DIR / "README.md"

# HotpotQA dev-distractor (CC BY-SA 4.0). The URL is the canonical mirror
# referenced by the official download.sh at maxbartolo/hotpot:
#   http://curtis.ml.cmu.edu/datasets/hotpot/hotpot_dev_distractor_v1.json
# If this becomes unreachable, alternative mirrors include
# https://hotpotqa.s3.amazonaws.com/... (currently returns 404) and
# huggingface.co/datasetshotpot_qa (community uploads). Update this constant
# and the cache SHA prefix will bust all eval caches automatically.
HOTPOTQA_URL = "http://curtis.ml.cmu.edu/datasets/hotpot/hotpot_dev_distractor_v1.json"

README_TEXT = """# HotpotQA Library Data

Dataset: HotpotQA dev_distractor v1 (multi-hop QA over Wikipedia).
Source: https://hotpotqa.github.io/
License: CC BY-SA 4.0.

This directory contains one Markdown file per question, generated by
`scripts/ingest_hotpotqa.py`. Files contain paragraph text from the original
dataset; questions, gold answers, and gold supporting facts are NOT included
in any file (kept in the source JSON only — see `scripts/.cache/`).

If you redistribute these files, retain this README.
"""


def download_or_use_cache(force: bool) -> Path:
    """Download the JSON if absent or `force` is True; cache it at CACHE_PATH.
    Returns CACHE_PATH on success. Exits 1 with download URL on repeated failure."""
    if CACHE_PATH.exists() and not force:
        return CACHE_PATH
    CACHE_PATH.parent.mkdir(parents=True, exist_ok=True)
    last_err: Exception | None = None
    for attempt in (0, 1):
        try:
            import urllib.request

            req = urllib.request.Request(
                HOTPOTQA_URL, headers={"User-Agent": "agent_html/iter-9"}
            )
            with urllib.request.urlopen(req, timeout=60) as resp:
                data = resp.read()
            CACHE_PATH.write_bytes(data)
            return CACHE_PATH
        except Exception as e:
            last_err = e
            if attempt == 0:
                time.sleep(5)
    print(
        f"Download failed after 2 attempts: {last_err}\nURL: {HOTPOTQA_URL}",
        file=sys.stderr,
    )
    sys.exit(1)


def slugify(qid: str) -> str:
    """Replace anything outside [A-Za-z0-9_-] with '_'. HotpotQA _id values
    are typically hex hashes that already conform; this is defensive."""
    out: list[str] = []
    for c in qid:
        if c.isalnum() or c in "-_":
            out.append(c)
        else:
            out.append("_")
    return "".join(out)


def stratified_sample(items: list[dict], n: int, seed: int = 42) -> list[dict]:
    """Same 6-bucket deterministic sampling as backend/eval/hotpotqa.py::sample.

    Inlined in this script so the ingest CLI has no path dependency on
    backend.eval at module-import time. Behavior is identical (same seed,
    same RNG instance, same per_bucket cap). The dedicated unit test in
    backend/tests/eval/test_hotpotqa.py covers the helper logic.
    """
    rng = random.Random(seed)
    buckets: dict[tuple[str, str], list[dict]] = {}
    for it in items:
        buckets.setdefault((it["type"], it["level"]), []).append(it)
    per = max(1, -(-n // 6))
    out: list[dict] = []
    for bucket in buckets.values():
        rng.shuffle(bucket)
        out.extend(bucket[:per])
    out = out[:n]
    rng.shuffle(out)
    return out


def write_question_file(item: dict, dest_dir: Path) -> None:
    qid = slugify(item["_id"])
    frontmatter = (
        "---\n"
        f"question_id: {item['_id']}\n"
        f"question_type: {item['type']}\n"
        f"question_level: {item['level']}\n"
        "source: hotpotqa\n"
        "---\n\n"
    )
    body_parts: list[str] = []
    for title, sentences in item["context"]:
        text = " ".join(sentences).strip()
        if not text:
            continue
        body_parts.append(f"# {title}\n{text}\n")
    full = frontmatter + "\n".join(body_parts)

    # Atomic write: tmp in the same dir, then os.replace.
    fd, tmp_path = tempfile.mkstemp(
        dir=str(dest_dir), prefix=f".{qid}.", suffix=".tmp"
    )
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as f:
            f.write(full)
        os.replace(tmp_path, dest_dir / f"{qid}.md")
    except Exception:
        try:
            os.unlink(tmp_path)
        except OSError:
            pass
        raise


def main(argv: list[str] | None = None) -> int:
    logging.basicConfig(
        level=logging.INFO, format="%(asctime)s %(levelname)s %(name)s %(message)s"
    )
    parser = argparse.ArgumentParser(
        description="Ingest HotpotQA dev distractor into the library."
    )
    grp = parser.add_mutually_exclusive_group()
    grp.add_argument(
        "--subset",
        type=int,
        metavar="N",
        help="Stratified sample of N questions (default if --full is also passed: --full wins)",
    )
    grp.add_argument(
        "--full", action="store_true", help="Use all 7,405 questions (default)"
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Re-download the dataset even if cached",
    )
    args = parser.parse_args(argv)

    if args.subset is not None and args.subset <= 1:
        parser.error("--subset must be >= 2")

    print(
        "Dataset: HotpotQA dev_distractor v1 "
        "(CC BY-SA 4.0 — https://hotpotqa.github.io/)"
    )
    json_path = download_or_use_cache(args.force)
    log.info("Loaded %d bytes from %s", json_path.stat().st_size, json_path.name)

    raw_items = json.loads(json_path.read_text(encoding="utf-8"))
    items = raw_items
    if args.subset is not None:
        items = stratified_sample(items, args.subset)
    log.info("Writing %d question files to %s", len(items), LIBRARY_DIR)

    LIBRARY_DIR.mkdir(parents=True, exist_ok=True)
    if not README_PATH.exists():
        README_PATH.write_text(README_TEXT, encoding="utf-8")

    skipped: list[str] = []
    written = 0
    for it in items:
        try:
            write_question_file(it, LIBRARY_DIR)
            written += 1
        except Exception as e:
            log.warning("Skipping qid=%s: %s", it.get("_id"), e)
            skipped.append(it.get("_id", "?"))
    log.info("Done: %d written, %d skipped", written, len(skipped))
    if skipped:
        preview = ", ".join(skipped[:10])
        log.warning(
            "Skipped IDs (first 10): %s%s",
            preview,
            "..." if len(skipped) > 10 else "",
        )
    return 0


if __name__ == "__main__":
    sys.exit(main())
