"""Convert MultiHop-RAG into a HotpotQA-shaped fixture for cross-dataset RAG eval.

MultiHop-RAG (Tang & Yang, COLM 2024, ODC-BY) is a multi-hop QA dataset
over news articles. Its natural evaluation is open-domain retrieval over a
609-document corpus, but our existing RAG eval pipeline
(`scripts/eval_qa_hotpotqa.py`) is built around the HotpotQA-style
"10 paragraphs per question" model. To reuse that pipeline, this script
synthesizes a per-question context of evidence_list docs + sampled
distractor docs, then writes a fixture in the same JSON shape as the
HotpotQA dev_distractor.

The fixture is fed to `scripts/eval_qa_hotpotqa.py` via `--fixture`; the
dataset_sha (file-hash prefix) ensures a separate FAISS cache namespace
from the HotpotQA run.

Output: scripts/.cache/multihop_rag_<subset>.json — same shape as
hotpot_dev_distractor_v1.json (list of HotpotQA-compatible records).
"""
from __future__ import annotations

import argparse
import json
import logging
import os
import random
import re
import sys
from pathlib import Path

log = logging.getLogger("ingest_multihop_rag")

REPO_ROOT = Path(__file__).resolve().parent.parent
BACKEND_ROOT = REPO_ROOT / "backend"
DEFAULT_DATASET_DIR = REPO_ROOT / "scripts" / ".cache" / "multihop_rag"
CACHE_PATH = DEFAULT_DATASET_DIR / "corpus.json"
QA_PATH = DEFAULT_DATASET_DIR / "MultiHopRAG.json"
FIXTURE_DIR = REPO_ROOT / "scripts" / ".cache"

# MultiHop-RAG canonical URLs (from yixuantt/MultiHop-RAG repo).
# License: ODC-BY (https://opendatacommons.org/licenses/by/1-0/).
CORPUS_URL = (
    "https://raw.githubusercontent.com/yixuantt/MultiHop-RAG/main/dataset/corpus.json"
)
QA_URL = (
    "https://raw.githubusercontent.com/yixuantt/MultiHop-RAG/main/dataset/MultiHopRAG.json"
)

# Match the HotpotQA distractor setting: 10 paragraphs per question
# (2-4 evidence + 6-8 distractor). This keeps the per-question FAISS
# cache size comparable to the HotpotQA eval so cross-dataset numbers
# are directly comparable.
PARAGRAPHS_PER_QUESTION = 10

# Map MultiHop-RAG question_type -> HotpotQA "type" field. HotpotQA uses
# "bridge" / "comparison" but the eval pipeline doesn't actually filter
# on this — it's only used in `random.Random(42)` stratified sampling.
TYPE_MAP = {
    "inference_query": "inference",
    "comparison_query": "comparison",
    "temporal_query": "temporal",
    "null_query": "null",
}

# Map evidence_list length -> HotpotQA "level" field. Used for stratified
# sampling only. null_query is the "no answer" case; we mark it "hard".
def _level_for(n_evidence: int) -> str:
    if n_evidence == 0:
        return "hard"
    if n_evidence == 2:
        return "easy"
    if n_evidence == 3:
        return "medium"
    return "hard"  # 4 evidence


README_TEXT = """\
# MultiHop-RAG Fixture

Dataset: MultiHop-RAG (Tang & Yang, COLM 2024).
Source: https://github.com/yixuantt/MultiHop-RAG
License: ODC-BY (https://opendatacommons.org/licenses/by/1-0/).

This fixture is generated by `scripts/ingest_multihop_rag.py` from the
original `corpus.json` + `MultiHopRAG.json`. The fixture is shaped like
HotpotQA's dev_distractor JSON so it can be fed directly to
`scripts/eval_qa_hotpotqa.py` via `--fixture`. The original 609-document
corpus is reduced to a per-question context of 10 paragraphs (2-4 gold
+ 6-8 sampled distractors); the rest of the corpus is dropped.

MultiHop-RAG is licensed separately from this project's HotpotQA
evaluation. The ODC-BY attribution is preserved here; redistribution
of any derived fixture must retain this README and the ODC-BY notice.
"""


def split_into_sentences(body: str) -> list[str]:
    """Naive sentence splitter for the news-article body.

    MultiHop-RAG bodies don't have structured sentence indices like
    HotpotQA, so we split on `[.!?]` followed by whitespace and a
    capital letter / digit / opening quote. Whitespace is normalized.
    Sentences that are just whitespace or punctuation are dropped.
    """
    # Normalize whitespace; protect against Unicode bullets/em-dashes
    # which are common in news prose.
    text = re.sub(r"\s+", " ", body).strip()
    if not text:
        return []
    # Split on sentence terminators, keep the terminator on the previous chunk.
    parts = re.split(r"(?<=[.!?])\s+(?=[A-Z0-9\"'(\[])", text)
    out: list[str] = []
    for p in parts:
        s = p.strip()
        if not s:
            continue
        # Reject single-token "sentences" that are just punctuation.
        if len(s) < 3 and not re.search(r"[A-Za-z0-9]", s):
            continue
        out.append(s)
    return out


def load_corpus(corpus_path: Path) -> dict[str, dict]:
    """Returns {title: corpus_doc}."""
    with corpus_path.open(encoding="utf-8") as f:
        corpus = json.load(f)
    return {d["title"]: d for d in corpus}


def stratified_sample(
    qa_items: list[dict], n: int, seed: int = 42
) -> list[dict]:
    """Stratified sample by question_type (4 buckets). Per-bucket cap
    is min(ceil(n/4), len(bucket)); the sampled set is deterministically
    shuffled. Identical contract to backend/eval/hotpotqa.py::sample
    so cross-dataset stratified runs behave consistently.
    """
    if n <= 1:
        raise ValueError("sample n must be >= 2")
    rng = random.Random(seed)
    buckets: dict[str, list[dict]] = {}
    for it in qa_items:
        buckets.setdefault(it["question_type"], []).append(it)
    per = max(1, -(-n // 4))
    sampled: list[dict] = []
    for bucket in buckets.values():
        rng.shuffle(bucket)
        sampled.extend(bucket[:per])
    sampled = sampled[:n]
    rng.shuffle(sampled)
    return sampled


def build_record(
    qa_item: dict,
    title_to_doc: dict[str, dict],
    rng: random.Random,
) -> dict | None:
    """Build a HotpotQA-shaped record for one MultiHop-RAG query.

    Returns None if the query's evidence_list references titles not in
    the corpus (should not happen with the official dataset, but a
    defensive check).
    """
    evidence_list = qa_item.get("evidence_list", [])
    evidence_titles: list[str] = []
    for ev in evidence_list:
        title = ev["title"]
        if title not in title_to_doc:
            # Fall back to skipping this evidence item rather than
            # failing the whole query.
            continue
        evidence_titles.append(title)
    # Filter for unique titles (the dataset sometimes lists the same
    # title twice in evidence_list when the same doc supports two
    # different facts).
    evidence_titles = list(dict.fromkeys(evidence_titles))

    n_distractor = max(0, PARAGRAPHS_PER_QUESTION - len(evidence_titles))
    pool = [t for t in title_to_doc.keys() if t not in evidence_titles]
    rng.shuffle(pool)
    distractor_titles = pool[:n_distractor]

    context_titles = evidence_titles + distractor_titles
    context: list[list] = []
    supporting_facts: list[list] = []
    for title in context_titles:
        body = title_to_doc[title].get("body", "")
        sentences = split_into_sentences(body)
        context.append([title, sentences])
        if title in evidence_titles:
            # Sentence index 0 is the first non-empty sentence; the
            # gold_paragraph_in_top_k metric only checks title membership,
            # so the sentence index is informational only.
            supporting_facts.append([title, 0])

    return {
        "_id": f"mhrag_{qa_item.get('query_id', '') or qa_item.get('id', '') or _short_hash(qa_item['query'])}",
        "question": qa_item["query"],
        "answer": qa_item["answer"],
        "type": TYPE_MAP.get(qa_item["question_type"], "other"),
        "level": _level_for(len(evidence_titles)),
        "context": context,
        "supporting_facts": supporting_facts,
    }


def _short_hash(text: str) -> str:
    """Stable 8-char hash of a question, used as a fallback id when the
    upstream dataset doesn't ship a query_id field."""
    import hashlib
    return hashlib.sha256(text.encode("utf-8")).hexdigest()[:8]


def main(argv: list[str] | None = None) -> int:
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s %(levelname)s %(name)s %(message)s",
    )
    parser = argparse.ArgumentParser(
        description="Convert MultiHop-RAG into a HotpotQA-shaped fixture."
    )
    parser.add_argument(
        "--from-local",
        action="store_true",
        help=(
            "Use the corpus.json + MultiHopRAG.json already in "
            "scripts/.cache/multihop_rag/ (skip download)."
        ),
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Re-download even if the cached copy exists.",
    )
    parser.add_argument(
        "--subset",
        type=int,
        metavar="N",
        help=(
            "Stratified sample of N queries (default: all 2,556). "
            "Used for the n=334-style smoke eval; cross-dataset "
            "validation uses the same n as the HotpotQA iter-12..23 runs."
        ),
    )
    parser.add_argument(
        "--full",
        action="store_true",
        help="Use all 2,556 queries (default).",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=None,
        help=(
            "Output fixture path. Default: "
            "scripts/.cache/multihop_rag_fixture_<n>.json (where n is "
            "'full' or the subset value)."
        ),
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=42,
        help="Random seed for stratified sampling and distractor selection.",
    )
    args = parser.parse_args(argv)

    DEFAULT_DATASET_DIR.mkdir(parents=True, exist_ok=True)
    FIXTURE_DIR.mkdir(parents=True, exist_ok=True)

    if not args.from_local:
        import requests
        for url, dest in [(CORPUS_URL, CACHE_PATH), (QA_URL, QA_PATH)]:
            if dest.exists() and not args.force:
                log.info("Using cached %s", dest.name)
                continue
            log.info("Downloading %s -> %s", url, dest)
            resp = requests.get(url, timeout=60)
            resp.raise_for_status()
            dest.write_bytes(resp.content)
    else:
        if not CACHE_PATH.exists() or not QA_PATH.exists():
            print(
                "--from-local requires both corpus.json and MultiHopRAG.json "
                f"in {DEFAULT_DATASET_DIR}",
                file=sys.stderr,
            )
            return 1

    print("Dataset: MultiHop-RAG (Tang & Yang, COLM 2024) — ODC-BY")
    title_to_doc = load_corpus(CACHE_PATH)
    qa_items = json.loads(QA_PATH.read_text(encoding="utf-8"))
    log.info(
        "Loaded %d corpus docs and %d QA pairs", len(title_to_doc), len(qa_items)
    )

    if args.subset is not None:
        if args.subset <= 1:
            parser.error("--subset must be >= 2")
        items = stratified_sample(qa_items, args.subset, seed=args.seed)
    else:
        items = qa_items
    log.info("Building fixture for %d queries", len(items))

    rng = random.Random(args.seed)
    records: list[dict] = []
    skipped: list[str] = []
    for qa in items:
        rec = build_record(qa, title_to_doc, rng)
        if rec is None:
            skipped.append(str(qa.get("query_id", "?")))
            continue
        records.append(rec)
    log.info("Built %d records, %d skipped", len(records), len(skipped))

    label = "full" if args.subset is None else str(args.subset)
    out_path = args.output or (FIXTURE_DIR / f"multihop_rag_fixture_{label}.json")
    out_path.write_text(json.dumps(records, ensure_ascii=False, indent=0), encoding="utf-8")
    log.info("Wrote fixture to %s (%d records, %.1f KB)", out_path, len(records), out_path.stat().st_size / 1024)

    readme_path = out_path.with_suffix(".README.md")
    if not readme_path.exists():
        readme_path.write_text(README_TEXT, encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main())
