from backend.rag.splitter import make_splitter, _read_text, _walk_library
from pathlib import Path


def test_make_splitter_returns_recursive_text_splitter():
    s = make_splitter(chunk_size=100, chunk_overlap=20)
    chunks = s.split_text("a" * 250)
    # 250 chars with 100/20 chunking → at least 3 chunks
    assert len(chunks) >= 3
    # Each chunk is <= chunk_size (approximately)
    for c in chunks:
        assert len(c) <= 120  # 100 + 20 overlap tolerance


def test_make_splitter_respects_overlap():
    s = make_splitter(chunk_size=100, chunk_overlap=50)
    text = "".join(str(i) for i in range(200))
    chunks = s.split_text(text)
    # With 50-char overlap, 200-char text produces 3 chunks
    assert len(chunks) >= 2


def test_read_text_supports_md_and_txt(tmp_path):
    f = tmp_path / "a.md"
    f.write_text("# Hello", encoding="utf-8")
    assert _read_text(f) == "# Hello"

    g = tmp_path / "b.txt"
    g.write_text("plain text", encoding="utf-8")
    assert _read_text(g) == "plain text"


def test_read_text_supports_pdf(tmp_path):
    """Smoke test: PDF parsing produces non-empty text from a real PDF.
    Uses a minimal inline PDF generated by pypdf's test fixtures, or by
    constructing a one-page PDF in memory."""
    try:
        from pypdf import PdfWriter
    except ImportError:
        import pytest
        pytest.skip("pypdf not installed")

    pdf_path = tmp_path / "doc.pdf"
    writer = PdfWriter()
    writer.add_blank_page(width=72, height=72)
    with open(pdf_path, "wb") as f:
        writer.write(f)
    # blank page has no extractable text — just verify it doesn't raise
    _read_text(pdf_path)


def test_walk_library_finds_supported_files(tmp_path):
    (tmp_path / "a.md").write_text("a")
    (tmp_path / "b.txt").write_text("b")
    (tmp_path / "c.pdf").write_text("dummy")  # extension-only check
    (tmp_path / "d.html").write_text("<p>d</p>")
    (tmp_path / "e.bin").write_text("skip me")
    (tmp_path / "sub").mkdir()
    (tmp_path / "sub" / "f.md").write_text("f")

    found = _walk_library(tmp_path)
    names = {p.name for p in found}
    assert names == {"a.md", "b.txt", "c.pdf", "d.html", "f.md"}
    assert "e.bin" not in names
